app_user_homepage:
    path:     /hello/{name}
    defaults: { _controller: AppUserBundle:Default:index }

sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /admin