parameters:
#    app_user.example.class: App\UserBundle\Example

services:
    app_user.registration.form.type:
        class: App\UserBundle\Form\Type\RegistrationFormType
        tags:
            - { name: form.type, alias: app_user_registration }
#services:
#    app_user.example:
#        class: %app_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
