imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: @AppBackendBundle/Resources/config/admin.yml }
#    - { resource: services.xml }
    - { resource: ../bundles/fos_user.yml }
    - { resource: ../bundles/sonata_admin.yml }
    - { resource: ../bundles/sonata_block.yml }
    - { resource: ../bundles/sonata_cache.yml }
    - { resource: ../bundles/sonata_core.yml }
    - { resource: ../bundles/sonata_formatter.yml }
    - { resource: ../bundles/sonata_user.yml }
    - { resource: ../bundles/sonata_seo.yml }
    - { resource: ../bundles/sonata_media.yml }
    - { resource: ../bundles/knp_menu.yml }
    - { resource: ../bundles/sonata_notification.yml }
    - { resource: ../bundles/jms_serializer.yml }
    - { resource: ../bundles/sonata_timeline.yml }
    - { resource: ../bundles/sonata_page.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~

    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme

    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~

    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    # Sonata User
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'
    # Fin Sonata User

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

        # Config de Sonata-User
        types:
            json: Sonata\Doctrine\Types\JsonType
        # Fin Config de Sonata-User

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
#        entity_managers:
#            default:
#                mappings:
                    # ...
#                    ApplicationSonataUserBundle: ~
#                    SonataUserBundle: ~

#                    FOSUserBundle: ~ # If SonataUserBundle extends it

#                    SonataNotificationBundle: ~
#                    ApplicationSonataNotificationBundle: ~

#                    SonataMediaBundle: ~
#                    ApplicationSonataMediaBundle: ~

#                    ApplicationSonataPageBundle: ~
#                    SonataPageBundle: ~

#                    ApplicationSonataTimelineBundle: ~
#                    SonataTimelineBundle: ~

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }
