sexo:
    path:     /
    defaults: { _controller: "AppBackendBundle:Sexo:index" }

sexo_show:
    path:     /{id}/show
    defaults: { _controller: "AppBackendBundle:Sexo:show" }

sexo_new:
    path:     /new
    defaults: { _controller: "AppBackendBundle:Sexo:new" }

sexo_create:
    path:     /create
    defaults: { _controller: "AppBackendBundle:Sexo:create" }
    requirements: { _method: post }

sexo_edit:
    path:     /{id}/edit
    defaults: { _controller: "AppBackendBundle:Sexo:edit" }

sexo_update:
    path:     /{id}/update
    defaults: { _controller: "AppBackendBundle:Sexo:update" }
    requirements: { _method: post|put }

sexo_delete:
    path:     /{id}/delete
    defaults: { _controller: "AppBackendBundle:Sexo:delete" }
    requirements: { _method: post|delete }
