parameters:
#    app_backend.example.class: App\BackendBundle\Example

services:
#    app_backend.example:
#        class: %app_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
